DesafioBiblioteca/Controllers/AuthorController.cs
using DesafioBiblioteca.Dtos;
using DesafioBiblioteca.Filters;
using DesafioBiblioteca.Models;
using DesafioBiblioteca.Services.AuthorServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DesafioBiblioteca.Controllers
{
    [UsuarioLogado]
    public class AuthorController : Controller
    {

        private readonly IAuthorInterface _authorInterface;
        public AuthorController(IAuthorInterface authorInterface)
        {
            _authorInterface = authorInterface;
        }

        //getall
        public async Task<IActionResult> Index()
        {
            var retorno = await _authorInterface.BuscaTodosAutores();
            if (retorno.Dados.Any())
                return View(retorno.Dados);
            else
                TempData["MensagemErro"] = retorno.Message;

            return View();
        }
        //getbyid
		public async Task<IActionResult> Details(int id)
		{
			var retorno = await _authorInterface.BuscaAuthorPorId(id);
			if (retorno.Dados!= null)
            {
                TempData["QtdLivros"] = await _authorInterface.BuscaQtdLivrosPublicados(id);
				return View(retorno.Dados);
            }
			else
				TempData["MesagemErro"] = retorno.Message;

			return RedirectToAction(nameof(Index));
		}

		public IActionResult Create()
		{
			return View();
		}

        [HttpPost]
        public async Task<IActionResult> Create(AuthorDto authorDto)
        {
            if (ModelState.IsValid)
            {
                var retorno = await _authorInterface.RegistrarAuthor(authorDto);
                if (!retorno.status)
                {
                    TempData["MensagemErro"] = retorno.Message;
                    return View(authorDto);
                }
                TempData["MensagemSucesso"] = retorno.Message;
                return View(authorDto);
            }
            else
                return View(authorDto);
		}

        public async Task<IActionResult> Edit(int id)
        {
			var retorno = await _authorInterface.BuscaAuthorPorId(id);
			if (retorno.Dados != null)
				return View(retorno.Dados);
			else
				TempData["MesagemErro"] = retorno.Message;

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, AuthorDto autorDto)
		{
			if (ModelState.IsValid)
			{
				var retorno = await _authorInterface.AlteraAutor(autorDto, id);
				if (!retorno.status)
				{
					TempData["MensagemErro"] = retorno.Message;
					return View(retorno.Dados);
				}
				TempData["MensagemSucesso"] = retorno.Message;
				return View(retorno.Dados);
			}
			else
				return View(new Author { Nome = autorDto.Nome, CPF = autorDto.CPF, DataNascimento = autorDto.DataNascimento, Id = id});
		}

		public async Task<IActionResult> Delete(int id)
		{
			var retorno = await _authorInterface.BuscaAuthorPorId(id);
			if (!retorno.status)
			{
				TempData["MensagemErro"] = retorno.Message; 
				return View(viewName: "Index");
			}
			TempData["QtdLivros"] = await _authorInterface.BuscaQtdLivrosPublicados(id);
			return View(retorno.Dados);
		}

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var retorno =await  _authorInterface.DeletaAuthorLogico(id);

            if (!retorno.status)
                TempData["MensagemErro"] = string.IsNullOrEmpty(retorno.Message) ? "Houve um erro" : retorno.Message;
            else
                TempData["MensagemSucesso"] = retorno.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

DesafioBiblioteca/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DesafioBiblioteca.Database;
using DesafioBiblioteca.Models;
using DesafioBiblioteca.Services.BookServices;
using DesafioBiblioteca.Dtos;
using DesafioBiblioteca.Services.AuthorServices;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using DesafioBiblioteca.Filters;
using DesafioBiblioteca.Services.SessionServices;

namespace DesafioBiblioteca.Controllers
{
	[UsuarioLogado]
	public class BookController : Controller
	{
		private readonly IBookInterface _service;
		private readonly IAuthorInterface _author;

		public BookController(IBookInterface service, IAuthorInterface author)
		{
			_service = service;
			_author = author;
		}

		// GET: Book
		public async Task<IActionResult> Index()
		{
			var retorno = _service.BuscaTodosLivros().Result;
			var retornoVB = new Dictionary<int, string>();
			if (retorno.Dados != null && retorno.Dados.Count > 0)
				foreach (var item in retorno.Dados)
				{
					var nome = _author.BuscaAuthorPorId(item.Id).Result.Dados == null ? "Autor Desconhecido" : _author.BuscaAuthorPorId(item.Id).Result.Dados.Nome;

					retornoVB.Add(item.Id, nome);
				}
			ViewBag.LivroEscritor = retornoVB;
			return View(retorno);
		}

		// GET: Book/Details/5
		public async Task<IActionResult> Details(int id)
		{
			var retorno = _service.BuscaLivroPorId(id);
			if (!retorno.Result.status)
			{
				ViewBag.Return = retorno.Result;
				return View(viewName: "Index");
			}
			var nome = _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados == null ? "Autor Desconhecido"
                : _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados.Nome;

			ViewData["Autor"] = nome;
			return View(retorno.Result.Dados);
		}

		// GET: Book/Create
		public IActionResult Create()
		{
			var retorno = new Response<BookDto>();
			var autores = _author.BuscaTodosAutores().Result;

			// Passe os dados para a view
			if (autores.Dados == null || autores.Dados.Count == 0) return View();
			ViewBag.Autores = new SelectList(autores.Dados, "Id", "Nome");
			ViewBag.Retorno = retorno;
			return View();
		}

		// POST: Book/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Titulo,SubTitulo,AuthorId,Idioma,DataLancamento,Editora,Genero")] BookDto book)
		{
			if (ModelState.IsValid)
			{
				var retorno = await _service.RegistrarLivro(book);
				var autores = _author.BuscaTodosAutores().Result;

				// Passe os dados para a view
				if (autores.Dados == null || autores.Dados.Count == 0) return View();
				ViewBag.Autores = new SelectList(autores.Dados, "Id", "Nome");
				ViewBag.Retorno = retorno;
				return View(book);
			}
			return View(book);
		}

		// GET: Book/Edit/5
		public async Task<IActionResult> Edit(int id)
		{
            var retorno = _service.BuscaLivroPorId(id);
            if (!retorno.Result.status)
            {
                ViewBag.Return = retorno.Result;
                return View(viewName: "Index");
            }
            //var nome = _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados == null ? "Autor Desconhecido"
            //    : _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados.Nome;

            //ViewData["Autor"] = nome;

            var autores = _author.BuscaTodosAutores().Result;
            // Passe os dados para a view
            if (autores.Dados == null || autores.Dados.Count == 0) return View();
			
            ViewBag.AutoresEdit = new SelectList(autores.Dados, "Id", "Nome");
			ViewBag.RetornoEdit = new Response<BookDto>(); 

            return View(retorno.Result.Dados);
            //return View(nome);
		}

		// POST: Book/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Titulo,SubTitulo,AuthorId,Idioma,DataLancamento,Editora,Genero")] BookDto book)
		{
			if (ModelState.IsValid)
			{
				var retorno = await _service.AlteraLivro(book, id);
				ViewBag.RetornoEdit = retorno;
				return View();
			}
			return RedirectToAction(nameof(Edit), id);
		}

		// GET: Book/Delete/5
		public async Task<IActionResult> Delete(int id)
		{
			var retorno = _service.BuscaLivroPorId(id);
			if (!retorno.Result.status)
			{
				ViewBag.Return = retorno.Result;
				return View(viewName: "Index");
			}
			var nome = _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados == null ? "Autor Desconhecido"
                : _author.BuscaAuthorPorId(retorno.Result.Dados.AuthorId).Result.Dados.Nome;

			ViewData["Autor"] = nome;
            ViewBag.RetornoDel = new Response<BookDto>();
            return View(retorno.Result.Dados);
		}

		// POST: Book/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{

			var retorno = _service.DeletaLivro(id);
            ViewBag.RetornoDel = retorno.Result;

			if (!retorno.Result.status)
				TempData["MensagemErro"] = string.IsNullOrEmpty(retorno.Result.Message)?"Houve um erro" : retorno.Result.Message;
			else
				TempData["MensagemSucesso"] = retorno.Result.Message;
			return RedirectToAction(nameof(Index), retorno.Result);
		}

	}
}

DesafioBiblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Desafio Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesafioBiblioteca.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Desafio Biblioteca </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Livros <i class="glyphicon glyphicon-book"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Escritores <i class="glyphicon glyphicon-user"></i></a>
                        </li>
                        <li class="nav-item right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Sair">Sair <i class="glyphicon glyphicon-log-out"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div><br /><br />

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Desafio Biblioteca
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DesafioBiblioteca/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Desafio Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesafioBiblioteca.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Desafio Biblioteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Cadastrar">Cadastre-se</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>